services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: vocamana-db
    env_file:
      - ./docker/db/.env
    volumes:
      - ./db/goose:/root/goose
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    networks:
      vocamana:
        ipv4_address: 192.168.100.2
  test-db:
    build:
      # dbのDockerfileを使ってビルドする
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: vocamana-test-db
    env_file:
      - ./docker/test-db/.env
    volumes:
      - ./db/goose:/root/goose
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    networks:
      vocamana:
        ipv4_address: 192.168.100.4
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    container_name: vocamana-api
    depends_on:
      - db
    volumes:
      - ./api:/go/src/api
    ports:
      - "8081:8080"
    env_file:
      - ./docker/api/.env
    tty: true
    networks:
      vocamana:
        ipv4_address: 192.168.100.3
networks:
  vocamana:
    ipam:
      driver: default
      config: 
        - subnet: 192.168.100.0/24