services:
  db:
    build:
      context: ./db-container
      dockerfile: Dockerfile
    container_name: vocamana-db
    env_file:
      - ./db-container/docker-config/db/.env
    volumes:
      - ./db-container/db/goose:/root/goose
      - ./db-container/docker-config/db/initdb:/docker-entrypoint-initdb.d
    networks:
      vocamana:
        ipv4_address: 192.168.100.2
  test-db:
    build:
      # dbのDockerfileを使ってビルドする
      context: ./db-container
      dockerfile: Dockerfile
    container_name: vocamana-test-db
    env_file:
      - ./db-container/docker-config/test-db/.env
    volumes:
      - ./db-container/db/goose:/root/goose
      - ./db-container/docker-config/db/initdb:/docker-entrypoint-initdb.d
    networks:
      vocamana:
        ipv4_address: 192.168.100.4
  api:
    build:
      context: ./api-container
      dockerfile: Dockerfile
    container_name: vocamana-api
    depends_on:
      - db
    ports:
      - "8081:8080"
    env_file:
      - ./api-container/docker-config/.env
      - ./api-container/docker-config/test/.env
    tty: true
    networks:
      vocamana:
        ipv4_address: 192.168.100.3
networks:
  vocamana:
    ipam:
      driver: default
      config: 
        - subnet: 192.168.100.0/24